# Generated by Django 5.2.8 on 2026-01-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_bio_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/default/avatar.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
